from datetime import timedelta
from datetime import datetime, timezone, timedelta
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from app import db


class Investigator(UserMixin, db.Model):
    """
    Represents a user of the system.
    Inherits UserMixin from Flask-Login which provides
    default implementations for is_authenticated, is_active, etc.
    """
    __tablename__ = 'investigators'

    # Primary key
    id = db.Column(db.Integer, primary_key=True)

    # Basic profile
    full_name = db.Column(db.String(150), nullable=False)
    email = db.Column(db.String(150), unique=True, nullable=False)
    password_hash = db.Column(db.String(256), nullable=False)

    # Role determines what actions this investigator can perform
    # Admin           -> full access
    # Lead Investigator -> manage cases and evidence
    # Analyst         -> view and analyse evidence
    # Read-Only       -> view only
    role = db.Column(
        db.Enum('Admin', 'Lead Investigator', 'Analyst', 'Read-Only', name='roles'),
        nullable=False,
        default='Analyst'
    )

    # Cryptographic key pair for digital signatures
    # public_key is stored in the database for signature verification
    # private_key is stored encrypted; in production it should be stored
    # in a hardware security module or secure vault
    public_key = db.Column(db.Text, nullable=True)
    private_key_encrypted = db.Column(db.Text, nullable=True)

    # TOTP shared secret for multi-factor authentication (null = MFA off)
    _totp_secret = db.Column('totp_secret', db.String(255), nullable=True)

    @property
    def totp_secret(self):
        if not self._totp_secret:
            return None
        from app.logic.crypto import _fernet
        try:
            return _fernet().decrypt(self._totp_secret.encode('utf-8')).decode('utf-8')
        except Exception:
            return self._totp_secret  # Fallback for old plaintext secrets

    @totp_secret.setter
    def totp_secret(self, value):
        if value:
            from app.logic.crypto import _fernet
            self._totp_secret = _fernet().encrypt(value.encode('utf-8')).decode('utf-8')
        else:
            self._totp_secret = None

    # Soft delete: deactivating an account instead of deleting it
    # preserves the audit trail
    is_active = db.Column(db.Boolean, default=True, nullable=False)

    # ── Login lockout ─────────────────────────────────────────────────────
    # How many consecutive wrong passwords have been entered
    failed_login_count = db.Column(db.Integer, default=0, nullable=False)
    # When NULL the account is not locked; when set the account is locked
    # until this datetime
    locked_until = db.Column(db.DateTime, nullable=True)

    # Timestamps
    created_at = db.Column(db.DateTime, default=lambda: (datetime.now(timezone.utc) + timedelta(hours=2)).replace(tzinfo=None), nullable=False)
    updated_at = db.Column(db.DateTime, default=lambda: (datetime.now(timezone.utc) + timedelta(hours=2)).replace(tzinfo=None),
                           onupdate=lambda: (datetime.now(timezone.utc) + timedelta(hours=2)).replace(tzinfo=None), nullable=False)

    # ── Relationships ─────────────────────────────────────────────────────
    # Cases this investigator created
    cases_created = db.relationship('Case', foreign_keys='Case.created_by_id',
                                    backref='creator', lazy='dynamic')
    # Cases assigned to this investigator
    cases_assigned = db.relationship('Case', foreign_keys='Case.assigned_to_id',
                                     backref='assignee', lazy='dynamic')
    # Evidence items uploaded by this investigator
    evidence_uploaded = db.relationship('EvidenceItem',
                                        foreign_keys='EvidenceItem.uploaded_by_id',
                                        backref='uploader', lazy='dynamic')
    # Evidence items currently held by this investigator
    evidence_held = db.relationship('EvidenceItem',
                                    foreign_keys='EvidenceItem.current_holder_id',
                                    backref='current_holder', lazy='dynamic')
    # Audit records generated by this investigator
    audit_records = db.relationship('AuditRecord', backref='investigator',
                                    lazy='dynamic')

    # ── Password helpers ──────────────────────────────────────────────────
    def set_password(self, password):
        """Hash and store the password. Never store plaintext passwords."""
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        """Return True if the provided password matches the stored hash."""
        return check_password_hash(self.password_hash, password)

    # ── Lockout helpers ───────────────────────────────────────────────────
    def is_locked(self):
        """Return True if the account is currently locked out."""
        if self.locked_until is None:
            return False
        if (datetime.now(timezone.utc) + timedelta(hours=2)).replace(tzinfo=None) < self.locked_until:
            return True
        # Lockout has expired — clear it
        self.locked_until = None
        self.failed_login_count = 0
        return False

    def lockout_remaining_minutes(self):
        """Return the number of minutes remaining until the account unlocks."""
        if self.locked_until is None:
            return 0
        remaining = (self.locked_until - (datetime.now(timezone.utc) + timedelta(hours=2)).replace(tzinfo=None)).total_seconds()
        return max(0, int(remaining / 60) + 1)

    def record_failed_login(self, max_attempts=5, lockout_minutes=15):
        """
        Increment the failed login counter.
        If max_attempts is reached, lock the account for lockout_minutes.
        """
        self.failed_login_count = (self.failed_login_count or 0) + 1
        if self.failed_login_count >= max_attempts:
            self.locked_until = (datetime.now(timezone.utc) + timedelta(hours=2)).replace(tzinfo=None) + timedelta(minutes=lockout_minutes)

    def reset_login_attempts(self):
        """Clear the failed login counter and any lockout on successful login."""
        self.failed_login_count = 0
        self.locked_until = None

    # ── MFA helpers ───────────────────────────────────────────────────────
    def is_mfa_enabled(self):
        """True if this account has TOTP multi-factor authentication enabled."""
        return bool(self.totp_secret)

    # ── Role helpers ──────────────────────────────────────────────────────
    def is_admin(self):
        return self.role == 'Admin'

    def can_manage(self):
        """Lead Investigator and Admin can manage cases and evidence."""
        return self.role in ('Admin', 'Lead Investigator')

    def can_analyse(self):
        """Analyst, Lead Investigator, and Admin can analyse evidence."""
        return self.role in ('Admin', 'Lead Investigator', 'Analyst')

    # ── Flask-Login required method ───────────────────────────────────────
    def get_id(self):
        return str(self.id)

    def __repr__(self):
        return f'<Investigator {self.email} [{self.role}]>'

